name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test import
      run: |
        python -c "import flask; import chess; print('✅ All dependencies imported successfully')"

    - name: Validate package structure
      run: |
        python -c "
        import os
        required_files = ['app.py', 'requirements.txt', 'README.md']
        for file in required_files:
            if os.path.exists(file):
                print(f'✅ {file} exists')
            else:
                print(f'❌ {file} missing')
                exit(1)
        print('✅ Package structure validated')
        "

    - name: Check Flask app syntax
      run: |
        python -m py_compile app.py
        echo "✅ Flask application syntax is valid"